### ISSUE TITLE
are you Chinese? Do you accept the project?

### ISSUE THREAD

**Issue by obrua** [WilsonPhooYK/udemy-advanced-restapi-flask-python#1]

**Comment by WilsonPhooYK** [comment]
Hi,

Please go ahead and grab the files from here instead It's more extensive.
Feel free to upgrade and make it better.

It is just good enough for my needs.

Type hints for SQLAlchemy and psycopg2
<https://github.com/WilsonPhooYK/udemy-automated-software-testing-python/tree/main/section6_7/typings>

**Comment by obrua** [comment]
This is great! Thank you so much, I have succeeded

**Comment by WilsonPhooYK** [comment]
> This is great! Thank you so much, I have succeeded

Glad I helped!
